services:
  db:
    ports:
      - "1433:1433"
    build: ./db
    user: root
    environment:
      - SA_PASSWORD=Resgrid123!!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    volumes:
       - ./docker-data/sql/data:/var/opt/mssql/data
       - ./docker-data/sql/log:/var/opt/mssql/log
       - ./docker-data/sql/backup:/var/opt/mssql/backup